# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lars Lockefeer
email: info@larslockefeer.nl
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Lars Lockefeer; iOS Developer at Picnic.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.larslockefeer.nl" # the base hostname & protocol for your site
twitter_username: larslockefeer
github_username:  larslockefeer

# Build settings
markdown: kramdown
